miapizza/urls.py
from django.urls import path

from . import views


app_name = 'miapizza'
urlpatterns = [
    path('', views.IndexView, name='base'),
    path('login/', views.LoginView, name='login'),
    path('ingredients/', views.IngredientView, name='ingredients'),
    path('pizzas/', views.PizzaView, name='pizzas'),
    path('remove/', views.remove, name='remove'),
    path('add/', views.add, name='add'),
    path('removePizza/', views.removePizza, name='removePizza'),
    path('addPizza/', views.addPizza, name='addPizza'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('miapizza.urls', namespace='miapizza')),
    path('admin/', admin.site.urls, name='admin'),
]

miapizza/models.py
import datetime
import json


from django.db import models
from django.utils import timezone


class Ingredient(models.Model):
    class Unites(models.TextChoices):
        gramme = 'gramme(s)'
        unite = 'unité(s)'
        boite = 'boîte(s)'
    name = models.CharField(max_length=200)
    last_update = models.DateTimeField('Dernier mouvement')
    quentity = models.IntegerField(default=0)
    unit = models.CharField(max_length=10,choices=Unites.choices,default=Unites.gramme)
    def __str__(self):
        return self.name
        
class History(models.Model):
    message = models.CharField(max_length=200, null=True)
    style = models.CharField(max_length=200, null=True)

class Pizza(models.Model):
    name = models.CharField(max_length=200, null=True)
    ingredients = models.CharField(max_length=500)
    last_update = models.DateTimeField('Dernier mouvement')
    def set_ingredients(self, list):
        self.ingredients = json.dumps(list)
    def get_ingredients(self):
        return json.loads(self.ingredients)
    def __str__(self):
        return self.name

miapizza/forms.py
# authentication/forms.py
from django import forms

class LoginForm(forms.Form):
    username = forms.CharField(max_length=63,widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(max_length=63, widget=forms.PasswordInput(attrs={'class': 'form-control'}))

miapizza/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, authenticate
import difflib

from .models import Ingredient, Pizza, History
from . import forms

@login_required
def IndexView(request):
    template_name = 'miapizza/base.html'
    return render(request, template_name)

def LoginView(request):
    template_name = 'miapizza/login.html'
    form = forms.LoginForm()
    message = ''
    if request.method == 'POST':
        form = forms.LoginForm(request.POST)
        if form.is_valid():
            user = authenticate(
                username=form.cleaned_data['username'],
                password=form.cleaned_data['password'],
            )
            if user is not None:
                login(request, user)
                return redirect('miapizza:base')
            else:
                message = 'Login failed!'
    context = {'form': form, 'message': message}
    return render(request, template_name, context)

@login_required
def IngredientView(request):
    template_name = 'miapizza/ingredients.html'
    ingredients = Ingredient.objects.order_by('name')[:]
    last_history = {}
    if History.objects.exists():
        last_history = {
        'message' : History.objects.last().message,
        'style' : History.objects.last().style,
        }
        History.objects.last().delete()
    context = {
        'ingredients_list': ingredients,
        'last_history': last_history
    }
    return render(request, template_name, context)

@login_required
def PizzaView(request):
    template_name = 'miapizza/pizzas.html'
    pizzas = Pizza.objects.order_by('name')[:]
    last_history = {}
    if History.objects.exists():
        last_history = {
        'message' : History.objects.last().message,
        'style' : History.objects.last().style,
        }
        History.objects.last().delete()
    context = {
        'pizzas_list': pizzas,
        'last_history': last_history
    }
    return render(request, template_name, context)

def change(ingredient, number, sign):
    ingredient.quentity += abs(int(number)) * sign
    ingredient.last_update = timezone.now()
    ingredient.save()
    log(ingredient, number, sign)
    

def log(ingredient, number, sign):
    f= open("data/logs.txt","a")
    f.write(str(ingredient.last_update.strftime("%Y-%m-%d %H:%M:%S"))
        + " "
        + str(ingredient.name)
        + " : " 
        + str(number * sign)
        + " donc total de "
        + str(ingredient.quentity)
        + "\n")
    f.close()

def historique(object, number, sign):
    signe = ''
    if int(number) * sign <0:
        style_alert = "warning"
    else:
        style_alert = "success"
        signe = '+'
    History.objects.get_or_create( #get if user uses back button
        message = (
            "Stock actualisé de "
            + signe
            + str(int(number) * sign)
            + " "
            + str(object.name)
            + str(object.last_update.strftime(" à %H:%M:%S."))
        ),
        style = style_alert
    )
    
def changeIngredient(request, sign):
    ingredient = get_object_or_404(Ingredient, pk=request.POST['id'])
    number = request.POST['num']
    if ingredient.unit == Ingredient.Unites.gramme and sign == 1 and int(number) < 500:
        History.objects.get_or_create( #get if user uses back button
            message = "Impossible d'ajouter une valeur inférieur à 500 !",
            style = "danger"
        )
        return
    if number == '':
        number = '1'
    change(ingredient, number, sign)
    historique(ingredient, number, sign)
    
    
def remove(request):
    changeIngredient(request, -1)
    return HttpResponseRedirect(reverse('miapizza:ingredients'))

def add(request):
    changeIngredient(request, 1)
    return HttpResponseRedirect(reverse('miapizza:ingredients'))

def changePizza(request, sign):
    pizza = get_object_or_404(Pizza, pk=request.POST['id'])
    number = request.POST['num']
    ingredients = pizza.get_ingredients()
    if number == '':
        number = '1'
    for ingredient in list(ingredients):
        #object = get_object_or_404(Ingredient, name=ingredient)
        try:
            object = Ingredient.objects.get(name=ingredient) 
        except:
            ingredients_list = [ingre.name for ingre in Ingredient.objects.all()]
            most_accurate = difflib.get_close_matches(ingredient, ingredients_list, 1)
            error_message = "Error ingrédient \"" + ingredient + "\" introuvable !"
            if len(most_accurate) >= 1:
                error_message += " Vouliez vous écrire : \"" + most_accurate[0] + "\" ?"
            History.objects.get_or_create( #get if user uses back button
                message = error_message,
                style = "danger"
            )
            return
        change(object, str(ingredients[ingredient] * int(number)), sign)
    historique(pizza, number, sign)
    

def removePizza(request):
    changePizza(request, -1)
    return HttpResponseRedirect(reverse('miapizza:pizzas'))

def addPizza(request):
    changePizza(request, 1)
    return HttpResponseRedirect(reverse('miapizza:pizzas'))

miapizza/templates/miapizza/base.html
<!DOCTYPE html>
<html lang="fr">
<head>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/custom.css' %}">
    <script src="{% static 'js/jquery-3.6.1.min.js' %}" type="text/javascript"></script>  
    <script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>  
    <title>Mia Pizza</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-danger">
        <a class="navbar-brand" href="{% url 'miapizza:base' %}">Mia Pizza</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'miapizza:pizzas' %}">Pizzas</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'miapizza:ingredients' %}">Ingredients</a>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
            </li>
          </ul>
        </div>
      </nav>
      <div class="mt-5">
        {% block content %}
        <div class="container text-center">
          <img src="{%static 'image/logo.png' %}" class="img-fluid">
        </div>
        {% endblock content%}
      </div>
</body>
</html>

miapizza/templates/miapizza/ingredients.html
{% extends 'miapizza/base.html' %}

{% block content %}
<div class="container">
{% if last_history %}
    <div class="alert alert-{{ last_history.style }} text-center" id="message_auto_hide">
        {{ last_history.message }}
    </div>
{% endif %}

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
{% if ingredients_list %}
    <div style="margin:10px;">
    <input type="text" class="form-control col-md-4 offset-md-4" id="search" autocomplete="off" onkeyup="filterFunction()" placeholder="Rechercher un ingrédient.." autofocus>
    </div>
    <div class="table-responsive">
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th class="text-center">Ingrédient</th>
                    <th class="text-center">Quantité</th>
                    <th class="text-center">Unité</th>
                    <th class="text-center">Ajout/Retrait</th>
                </tr>
            </thead>
            <tbody id="ingredients_list">
            {% for ingredient in ingredients_list %}
                <tr id="{{ ingredient.name }}">
                    <td class="text-center">
                        {{ ingredient.name }}
                    </td>
                    <td class="text-center">
                        {{ ingredient.quentity }}
                    </td>
                    <td class="text-center">
                        {{ ingredient.unit }}
                    </td>
                    <td class="d-flex justify-content-center">  
                        <form class="input-group-append text-center" action="{% url 'miapizza:add' %}" method="post" autocomplete="off">
                            {% csrf_token %}
                            <input type="hidden" name="id" value="{{ ingredient.id }}"><br>
                            <input type="number" name="num">
                            <input type="submit" value="Add" class="btn btn-success ml-2">
                            <input type="submit" value="Remove" class="btn btn-outline-danger ml-2" formaction="{% url 'miapizza:remove' %}" method="post">
                        </form>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% else %}
    <p>Pas d'ingrédients disponible. Base de donnée vide !</p>
{% endif %}
</div>

{% if ingredients_list %}
<script>/* Search filter https://www.w3schools.com/howto/howto_js_filter_lists.asp */
function filterFunction() {
    // Declare variables
    var input, filter, ul, li, i;
    input = document.getElementById('search');
    filter = input.value.toUpperCase();
    ul = document.getElementById("ingredients_list");
    li = ul.getElementsByTagName('tr');

    // Loop through all list items, and hide those who don't match the search query
    for (i = 0; i < li.length; i++) {
        if (li[i].id.toUpperCase().indexOf(filter) > -1) {
            li[i].style.display = "";
        } else {
            li[i].style.display = "none";
        }
    }
};
</script>

<style> /* Auto hide confirmation message https://stackoverflow.com/a/21994053 */
#message_auto_hide {
    animation: cssAnimation 0s ease-in 5s forwards;
    animation-fill-mode: forwards;
}
@keyframes cssAnimation {
    to {
        visibility:hidden;
    }
}
</style>
{% endif %}

{% endblock content %}

miapizza/templates/miapizza/login.html
{% extends 'miapizza/base.html' %}
{% block content %}
<div class="d-flex justify-content-center text-center">
    <p>{{ message }}</p>
    
    <form method="post">
        <div class="input-group mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text">Username</span>
            </div>
            {{ form.username}}
        </div>
        <div class="input-group mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text">Password</span>
            </div>
            {{ form.password}}
        </div>
        {% csrf_token %}
        <button class="btn btn-primary"type="submit" >Submit</button>
    </form>
</div>
{% endblock content %}

miapizza/templates/miapizza/pizzas.html
{% extends 'miapizza/base.html' %}

{% block content %}
<div class="container">
{% if last_history %}
    <div class="alert alert-{{ last_history.style }} text-center" id="message_auto_hide">
        {{ last_history.message }}
    </div>
{% endif %}

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
{% if pizzas_list %}
    <div style="margin:10px;">
    <input type="text" class="form-control col-md-4 offset-md-4" id="search" autocomplete="off" onkeyup="filterFunction()" placeholder="Rechercher une pizza.." autofocus>
    </div>

    <table class="table table-striped table-hover">
    <thead>
        <tr>
            <th class="text-center">Pizza</th>
            <th class="text-center">Ajout/Retrait</th>
        </tr>
    </thead>
    <tbody id="pizzas_list">
    {% for pizza in pizzas_list %}
        <tr id="{{ pizza.name }}">
            <td class="text-center">
                {{ pizza.name }}
            </td>
            <td>
                <form class="input-group-append justify-content-center" action="{% url 'miapizza:removePizza' %}" method="post" autocomplete="off">
                    {% csrf_token %}
                    <input type="hidden" name="id" value="{{ pizza.id }}"><br>
                    <input type="number" name="num" min="-100" max="100">
                    <input type="submit" value="Remove" class="btn btn-danger ml-2">
                    <input type="submit" value="Add" class="btn btn-outline-success ml-2" formaction="{% url 'miapizza:addPizza' %}" method="post">
                </form>
            </td>
        </tr>
    {% endfor %}
    </tbody>
    </table>
{% else %}
    <p>Pas de pizzas disponible. Base de donnée vide !</p>
{% endif %}
</div>

{% if pizzas_list %}
<script>/* Search filter https://www.w3schools.com/howto/howto_js_filter_lists.asp */
function filterFunction() {
    // Declare variables
    var input, filter, ul, li, i;
    input = document.getElementById('search');
    filter = input.value.toUpperCase();
    ul = document.getElementById("pizzas_list");
    li = ul.getElementsByTagName('tr');

    // Loop through all list items, and hide those who don't match the search query
    for (i = 0; i < li.length; i++) {
        if (li[i].id.toUpperCase().indexOf(filter) > -1) {
            li[i].style.display = "";
        } else {
            li[i].style.display = "none";
        }
    }
};
</script>

<style> /* Auto hide confirmation message https://stackoverflow.com/a/21994053 */
#message_auto_hide {
    animation: cssAnimation 0s ease-in 5s forwards;
    animation-fill-mode: forwards;
}
@keyframes cssAnimation {
    to {
        visibility:hidden;
    }
}
</style>
{% endif %}
{% endblock content %}